server:
  port: 4551
  shutdown: "graceful"

# If you use a database then uncomment the `group:, readiness: and include: "db"` lines in the health probes and uncomment the datasource section
management:
  endpoint:
    health:
      show-details: "always"
      # group:
      #  readiness:
      #   include: "db"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus

springdoc:
  packagesToScan: uk.gov.hmcts.reform.external-api.controllers
  writer-with-order-by-keys: true

spring:
  config:
    import: "optional:configtree:/mnt/secrets/opal/"
  application:
    name: Spring Boot Template
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}${DB_OPTIONS:}
#    username: ${DB_USER_NAME}
#    password: ${DB_PASSWORD}
#    properties:
#      charSet: UTF-8
#    hikari:
#      minimumIdle: 2
#      maximumPoolSize: 10
#      idleTimeout: 10000
#      poolName: {to-be-defined}HikariCP
#      maxLifetime: 7200000
#      connectionTimeout: 30000
#  jpa:
#    properties:
#      hibernate:
#        jdbc:
#          lob:
#            # silence the 'wall-of-text' - unnecessary exception throw about blob types
#            non_contextual_creation: true

azure:
  application-insights:
    instrumentation-key: ${opal.AppInsightsInstrumentationKey:00000000-0000-0000-0000-000000000000}

s2s:
  endpoints:
    opal-fines-service: ${OPAL_FINES_S2S_URL:http://localhost:4553/opal}
    opal-maintenance-service: ${OPAL_MAINTENANCE_S2S_URL:http://localhost:4554/opal}
  api:
    create-account: ${OPAL_S2S_CREATE_ACCOUNT_API:/api/createAccount}

soap:
  keystore:
    encoded-jks-string: ${OPAL_SOAP_JKS_STRING:/u3+7QAAAAIAAAACAAAAAgADY3BwAAABkKFZ9uMABVguNTA5AAADaTCCA2UwggJNoAMCAQICCHDrIDM2O0teMA0GCSqGSIb3DQEBCwUAMGExCzAJBgNVBAYTAlVLMRcwFQYDVQQIEw5HcmVhdGVyIExvbmRvbjEPMA0GA1UEBxMGTG9uZG9uMQwwCgYDVQQKEwNNT0oxDDAKBgNVBAsTA0dPQjEMMAoGA1UEAxMDQ1BQMB4XDTI0MDcxMTEwMTY1OFoXDTM0MDcwOTEwMTY1OFowYTELMAkGA1UEBhMCVUsxFzAVBgNVBAgTDkdyZWF0ZXIgTG9uZG9uMQ8wDQYDVQQHEwZMb25kb24xDDAKBgNVBAoTA01PSjEMMAoGA1UECxMDR09CMQwwCgYDVQQDEwNDUFAwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCksBBqudkp2ZvAx/PBgDDp266ULA3qAknw51nxUafYV5aMRnp0mwAl63+dwTSIIhVBNEjzQgbBf3VdVjHYGs40hmq2Z8AfWDw26a7W4kqiLlvK9++hFF3e8wYp3Dm1OlQOLDQjZSfluYuLdlGyN+vN5K9nTSEFDVgScOyi4VST9YtYezWEEEnaZGS7AkOSKhMR6SVr6kxJl86fftfvu4C/7AQR0jAq39cf3APsLdE5vnGd73qRhabKXzI8GTUd0TZ8TsYlJZ8J5YBb0NmxHKHqQgUOvfQD5ZRj47cuL6btSeshMclGOSbcut5rYpAphJnBntdMy201SUXeTQ6ss8VXAgMBAAGjITAfMB0GA1UdDgQWBBR/fJUYsuV29czew/y4/1yrftwwbjANBgkqhkiG9w0BAQsFAAOCAQEAk5vmP6cSfmXbVFycbOoAOHwVPzKbUq3JImxBHmXDvoF7EHdSyWB909/6L2GuyyFNNcR3ZeNNX0Bz0yxoZKy6u0WTWj+llazYyFMEQxnxnqjQ56Iy9kRme+0sKzCfUZGug3YEOllZjlQemmUPfSe8g9m1Tret9UlQItOh0kjsm1hTu8qEqxVSjFdl6n+UknweQll48o0R3VOB1Kfu3TUdFWnoWsupCkvELMxxuHrEMP5QDpjxWAuJb0htI3R0fOiI0zpnCz9MT+j1uoXUDa5GSPfiU9AZxJtt8L1Okpt/sOixq0ryXrqQNu+LPot3v044Qw0K3t33dacBjDcVbfBtrwAAAAEABG9wYWwAAAGQoVCdTwAABQAwggT8MA4GCisGAQQBKgIRAQEFAASCBOgXC4MLHlmnkcnbJWK8sgbOSPA8/SQiJ1PmOuJjZVUQaPbHcSbDYQWkQYZjpvut1vsim03WE4IcmAZ/GoD8meZJFVX5kABIllw4nWtb6DH955+U+i7cLNyiaQ0KJ/dm21TvST+SwRjzDCA9ZaiYCOk5UpUzNvD24jZ8ebpkzDhxqx17v276slCtAsbSrUjMDn2ZwvAJ0W/234RplI/HwJSyY2exNFu+ILmG3VclezOULOcLxvBvWztOkMdjtZocWq2nZZfZ5IuztObvBOxPreHl2hq2zZezn4y36mmE+uVcnDO4cGUHrJvpBDinm/Rjq+hghhs6SYcEMc97z1aXKQEdwKYcwXK/1nGoPtDQQdiCmEulQrYEQxgNMlJgVMlTKsAVxkovzJZuwpYToWFxO55TdNx53Pijpr7Vk6KXqSL4Ll0HxhojO5gvNaBDVyWeDhd5wNMLJS3L/Dd9K8ONrD96LdzK395jbSpnpyIKwYFXMQFoEfit9PzCr3KbXSz9zhtu3psTfgWNdcGNIJcDkXjHGbOmPwoB1mPNfmn8Awxic+tpZA9eSDbD8vN+ISIk0in7VIqtboUzWwmJgxqOpFqsf8cLzExSrrXGzxfLi192ZLUgJn+vW5T9oz5OgBZ2X6TOS5YqcVpWCV6c6BzZ16hY2ZuqkTFno79xZVJUyM3rD+GXHWRPNUTKU4gKbd8h1+5DZTRMdey5SLjMNvwIdznGPj3kXJQHaoGHes/eQ6N7pSW0NpYg6CMXK8WkR1SGOoBYbNZVV08HJucfi3Etwi0MAWaiiynxOvSMI75eKGmdCsAel2dD8XXQqO9VovsI8Nrx/BRRyA+KcDxiGId2V3aFiCSYx2Qv5AudvZ8eUu/QQ8PJfzZ+vK/42+ufoHgCA7kqWimGxKtrlz2SPswDY6DZD6BhcYvp4M4O76SYMjUiBqbV1kLMLe8nUaQ2ytoHmSMVXQb8C5HU7VG7UPYDZWaPiLk+O/4I4aRrvSI/cvEa2vHeouMKimvZ+iwugYKvhmpK0frgGKosEFE0TDIPbgNZZSmFNUCVFeXhidwTsQZpEssUy79fShH+7XU0AaguxFQo9S7qy0PFmQsoWE2O50pHMaFQ45sYRWk3jFrGwWVsSRS8pgYdosl0JjBsJCjuvsqfE9PFPs2JKgUOb1lI1v+7Prr7BG0yVqWZ1cLp0tjWZ0OKus3BNEMi+hnVGPlyS6ktgUjcy7+utEJ+ruAacIcCHQ7eR7kMTYIBk8NnC5HEiFqo/cMH04ARGdM5WTjE6Xl1VHF5NobnBzXM32qU7JhjSWOfnA3bjAWIpGPA+iLDnBn8wNo4Yhe/F27dr3HnVAEGz4cJxJ4724SyVKGure6jPv6j4wApYDd/Ayctkn411jzpyfWsUJJWw0ByPE4pAK1vqD1p2A9GrqfVq9m3bPwUgdrHpnqsHPH+nwJRJT0UIpKUEyfPOERQ/kk5dHsXJMZbomXTPCbHq+I0wvoFTOzEJz1v2qUmCdAcXYs2Ssf1jJrZeW2hHmj56g9jLfLC1qQYnGH5/kloPEgaxh+Xq2Xb1z2aO76fspKbo+eVc1YhmevccT2Wp5eAcOvaQfQ+y0fpL1deCCbNajn+g84JKPbsUhFvi8lrr64zMIEsk6MOuLApkATDUlP9J7cyDIG1+YmOASrnFWdzTwAAAAEABVguNTA5AAADcDCCA2wwggJUoAMCAQICCQCR57JHOZz1DjANBgkqhkiG9w0BAQsFADBkMQswCQYDVQQGEwJVSzEXMBUGA1UECBMOR3JlYXRlciBMb25kb24xDzANBgNVBAcTBkxvbmRvbjEMMAoGA1UEChMDQ0dJMQ4wDAYDVQQLEwVITUNUUzENMAsGA1UEAxMET3BhbDAeFw0yNDA3MTExMDIyMTNaFw0zNDA3MDkxMDIyMTNaMGQxCzAJBgNVBAYTAlVLMRcwFQYDVQQIEw5HcmVhdGVyIExvbmRvbjEPMA0GA1UEBxMGTG9uZG9uMQwwCgYDVQQKEwNDR0kxDjAMBgNVBAsTBUhNQ1RTMQ0wCwYDVQQDEwRPcGFsMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAjSpEO0TtarSR12nRShID+fjcU8Lll4Yj35yK7/ByevoRs5MZR4UVTbIVCRdisuDzhpMcWbXYrLihoA5u+gPVG0xYtvYg/Ipo2qmhP/bYcFPxG5p+LGYIpp4wJtMFOWrGGmZS+gsfTBxhM2Ae0MQPOHFOc4sQe7VNPaSYvgAz6KNz8aGr3NmK//M+tSXUyFOnjr/7eaCsWUmUUfjAIWTosjWOYAKHVDDKzIzjDQDjfkrKOCi3bAKtyeSw0UOQFKPUA1+Px26f6QaSfqLTimi55o9/BDYwCjSvUi5VpVMqqnGFCbFXKNWfwedjsfgF2IO34cw4cnmnbSreBMUPV2IWjQIDAQABoyEwHzAdBgNVHQ4EFgQUps8YLtXh9R5626ZA+itQvlbtIMQwDQYJKoZIhvcNAQELBQADggEBAHnSAW2v6X7ijU2WfEKcRwS4vp5hGwM5Noz5Uct7qXNa5TYfTXjpJXaBjL5IKCXxzHHwH1DR8Z2Lnvb7PJw4Q8BBWBHSmvuLBPFAyz3I/0lnODwtoYF9SrDCaKdHMWDy4FaIO6T4ZUEe/Im3+RpsPkQqpV0xViLCtlTSJKEjnuva4XkSUi/9BWGXFzsHwrAzj3OU64KcGF2FohTT2Mt4mESzS4ZBuCwyB/EjADwmQRUrnDJitGCmSo+uMqjOcQPmBkz8QQf7e2lOgCNl/Edjj0mhxwTXVc4uFx/5BgLx2jZIp5rl7ks+gw0lpndanGhdbqDEdOp8/jVZwJiRlQtTTCVctUVDPn9CLdqgAjVzTCxRrP5Sjw==}
    password: ${OPAL_SOAP_JKS_PASSWORD:password}
    aliases:
      private: ${OPAL_SOAP_PRIVATE_ALIAS:opal}
      public:
        cpp: ${CPP_TO_OPAL_SOAP_PUBLIC_ALIAS:cpp}
