java:
  applicationPort: 4551
  image: 'sdshmctpsublic.azurecr.io/opal/external-api:latest'
  ingressHost: opal-external-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  keyVaults:
    opal:
      secrets:
        - name: opal-soap-jks-string
          alias: OPAL_SOAP_JKS_STRING
        - name: opal-soap-jks-password
          alias: OPAL_SOAP_JKS_PASSWORD
environment:
  OPAL_FINES_S2S_URL: https://opal-fines-service.{{ .Values.global.environment }}.platform.hmcts.net
